org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
version_minecraft=1.20.1
version_forge=47.4.12
version_buildnumber=1
version_jei=15.20.0.112
version_ie=1.20.1-10.1.0-171
version_ig=0.5.4-b44
version_if=1.0.2
version_it=1.20.1-2.0.1-b4196-beta
stage=alpha
version_parchment=1.19.3-2023.06.25
mod_id=immersiveatomics

mod_license=GNU General Public License v3.0
mod_description=An Immersive Engineering add-on based around nuclear power.
mod_authors=MagneticPrism
mod_name=Immersive Atomics

